# Generated by Django 5.1 on 2024-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
