# Generated by Django 5.1 on 2024-08-15 09:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_employer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=cloudinary.models.CloudinaryField(default=True, max_length=255, verbose_name='cv'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default=True, max_length=255, verbose_name='avatar'),
            preserve_default=False,
        ),
    ]
