# Generated by Django 5.1 on 2024-09-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_service_employer_business_document_employerservice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerservice',
            name='employer',
        ),
        migrations.AddField(
            model_name='employerservice',
            name='user',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
