# Generated by Django 5.1 on 2024-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication_cv_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='phone',
            field=models.CharField(default=866695643, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=models.ManyToManyField(to='jobs.technology'),
        ),
    ]
