# Generated by Django 5.1 on 2024-08-29 11:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_employerdocument_business_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
