# Generated by Django 5.1 on 2024-08-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_seeker_technologies_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(upload_to='files/'),
        ),
    ]
