# Generated by Django 5.1 on 2024-09-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_jobapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location_detail',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
